[database]
path = "./Database/index.db"

[indexer]
root = "/home/denispescar"
ignore = [
    ".git",
    "__pycache__",
    ".venv",
    "*.pyc",
    ".idea",
    ".vscode",
    "*.pdf",
    "*.exe",
    "*.png",
    "*.jpg",
    "*.zip"
]

[search]
max_results = 20
snippet_tokens = 20
cache_ttl = 300
